// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace ExtraHotkeys
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "ExtraHotkeys";
        public const string Version     = "0.1.0";
        public const string Title       = "Extra Hotkeys";
        public const string Description = "This mod adds extra hotkeys to the game that should have been there by default.";
    }
}
